name: Build & Deploy
on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  NAME: digital_uncut_seo_alert

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Functions
        run: >-
          gcloud functions deploy ${{ env.NAME }}
          --entry-point=main
          --project=${{ secrets.PROJECT_ID }}
          --runtime=python38
          --trigger-http
          --service-account=${{ secrets.GCP_SA }}
          --set-env-vars=SENDER_EMAIL=${{ secrets.SENDER_EMAIL }},SENDER_PWD=${{ secrets.SENDER_PWD }}
